name: upload to 1fichier.com
description: 'upload file to 1fichier.com'
author: wrenth04

inputs:
  file:
    description: filename to upload
    required: true
    
outputs:
  url:
    value: ${{ steps.upload.outputs.url }}
  remove_url:
    value: ${{ steps.upload.outputs.remove_url }}

runs:
  using: composite
  steps:
    - name: upload to 1fichier.com
      id: upload
      shell: bash -e {0}
      run: |
        url=$(curl -s https://1fichier.com | grep upload.cgi | grep form)
        url=${url#*http}; url="http${url%%\"*}"
        id=${url##*=}
        host=${url%\/*}
        curl -s -X POST "$url" -F "file[]=@${{ inputs.file }}" -o /dev/null
        info_url="$host/end.pl?xid=$id"
        info=$(curl -s $info_url)
        download_link=${info#*Download link}
        download_link=${download_link#*http}; download_link="http${download_link%%\"*}"
        remove_link=$(echo "$info" | grep remove)
        remove_link=${remove_link#*>}; remove_link=${remove_link%%<*}
        echo "::set-output name=url::$download_link"
        echo "::set-output name=remove_url::$remove_link"
